# Creating a Siamese model using Trax: Ungraded Lecture Notebook

In [1]:
import trax
from trax import layers as tl
import trax.fastmath.numpy as np
import numpy

# Setting random seeds
trax.supervised.trainer_lib.init_random_number_generators(10)
numpy.random.seed(10)

INFO:tensorflow:tokens_length=568 inputs_length=512 targets_length=114 noise_density=0.15 mean_noise_span_length=3.0 


## L2 Normalization

Before building the model you will need to define a function that applies L2 normalization to a tensor. This is very important because in this week's assignment you will create a custom loss function which expects the tensors it receives to be normalized. Luckily this is pretty straightforward:

In [2]:
def normalize(x):
    return x / np.sqrt(np.sum(x * x, axis=-1, keepdims=True))

Notice that the denominator can be replaced by `np.linalg.norm(x, axis=-1, keepdims=True)` to achieve the same results and that Trax's numpy is being used within the function.

In [3]:
tensor = numpy.random.random((2,5))
print(f'The tensor is of type: {type(tensor)}\n\nAnd looks like this:\n\n {tensor}')

The tensor is of type: <class 'numpy.ndarray'>

And looks like this:

 [[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]
 [0.22479665 0.19806286 0.76053071 0.16911084 0.08833981]]


In [4]:
norm_tensor = normalize(tensor)
print(f'The normalized tensor is of type: {type(norm_tensor)}\n\nAnd looks like this:\n\n {norm_tensor}')

The normalized tensor is of type: <class 'jax.interpreters.xla.DeviceArray'>

And looks like this:

 [[0.57393795 0.01544148 0.4714962  0.55718327 0.37093794]
 [0.26781026 0.23596111 0.9060541  0.20146926 0.10524315]]


In [5]:
(norm_tensor**2).sum(axis=1)

DeviceArray([1.        , 0.99999994], dtype=float32)

# Notice that the initial tensor was converted from a numpy array to a jax array in the process.

## Siamese Model

To create a `Siamese` model you will first need to create a LSTM model using the `Serial` combinator layer and then use another combinator layer called `Parallel` to create the Siamese model. You should be familiar with the following layers (notice each layer can be clicked to go to the docs):
   - [`Serial`](https://trax-ml.readthedocs.io/en/latest/trax.layers.html#trax.layers.combinators.Serial) A combinator layer that allows to stack layers serially using function composition.
   - [`Embedding`](https://trax-ml.readthedocs.io/en/latest/trax.layers.html#trax.layers.core.Embedding) Maps discrete tokens to vectors. It will have shape `(vocabulary length X dimension of output vectors)`. The dimension of output vectors (also called `d_feature`) is the number of elements in the word embedding.
   - [`LSTM`](https://trax-ml.readthedocs.io/en/latest/trax.layers.html#trax.layers.rnn.LSTM) The LSTM layer. It leverages another Trax layer called [`LSTMCell`](https://trax-ml.readthedocs.io/en/latest/trax.layers.html#trax.layers.rnn.LSTMCell). The number of units should be specified and should match the number of elements in the word embedding.
   - [`Mean`](https://trax-ml.readthedocs.io/en/latest/trax.layers.html#trax.layers.core.Mean) Computes the mean across a desired axis. Mean uses one tensor axis to form groups of values and replaces each group with the mean value of that group.
   - [`Fn`](https://trax-ml.readthedocs.io/en/latest/trax.layers.html#trax.layers.base.Fn) Layer with no weights that applies the function f, which should be specified using a lambda syntax. 
   - [`Parallel`](https://trax-ml.readthedocs.io/en/latest/trax.layers.html#trax.layers.combinators.Parallel) It is a combinator layer (like `Serial`) that applies a list of layers in parallel to its inputs.

Putting everything together the Siamese model will look like this:

In [6]:
vocab_size = 500
model_dimension = 128

# Define the LSTM model
LSTM = tl.Serial(
        tl.Embedding(vocab_size=vocab_size, d_feature=model_dimension),
        tl.LSTM(model_dimension),
        tl.Mean(axis=1),
        tl.Fn('Normalize', lambda x: normalize(x))
    )

# Use the Parallel combinator to create a Siamese model out of the LSTM 
Siamese = tl.Parallel(LSTM, LSTM)

Next is a helper function that prints information for every layer (sublayer within `Serial`):

In [7]:
def show_layers(model, layer_prefix):
    print(f"Total layers: {len(model.sublayers)}\n")
    for i in range(len(model.sublayers)):
        print('========')
        print(f'{layer_prefix}_{i}: {model.sublayers[i]}\n')

print('Siamese model:\n')
show_layers(Siamese, 'Parallel.sublayers')

print('Detail of LSTM models:\n')
show_layers(LSTM, 'Serial.sublayers')

Siamese model:

Total layers: 2

Parallel.sublayers_0: Serial[
  Embedding_500_128
  LSTM_128
  Mean
  Normalize
]

Parallel.sublayers_1: Serial[
  Embedding_500_128
  LSTM_128
  Mean
  Normalize
]

Detail of LSTM models:

Total layers: 4

Serial.sublayers_0: Embedding_500_128

Serial.sublayers_1: LSTM_128

Serial.sublayers_2: Mean

Serial.sublayers_3: Normalize



Try changing the parameters defined before the Siamese model and see how it changes!

You will actually train this model in this week's assignment. For now you should be more familiarized with creating Siamese models using Trax. **Keep it up!**

# Version pytorch

In [8]:
import torch
import torch.nn as nn

In [9]:
embed = nn.Embedding(num_embeddings=5, embedding_dim=3)

In [10]:
x = torch.tensor([[1,2,3,4,0,0],
                     [1,1,1,0,0,0]])
x.shape

torch.Size([2, 6])

In [11]:
xe = embed(x)
xe.shape

torch.Size([2, 6, 3])

In [12]:
lstm = nn.LSTM(input_size=3, hidden_size=3) # trax a besoin que de la hidden_size

In [13]:
outputl, (hl, cl) = lstm(xe)
outputl.shape

torch.Size([2, 6, 3])

In [14]:
meanl = outputl.mean(axis=1)
meanl.shape


torch.Size([2, 3])

In [15]:
def normalize2(x):
    return x / torch.sqrt(torch.sum(x * x, axis=-1, keepdims=True))

In [16]:
normalize2(meanl)

tensor([[ 0.9318, -0.3000, -0.2045],
        [ 0.7691, -0.4271, -0.4755]], grad_fn=<DivBackward0>)

In [17]:
class Sub(nn.Module):
    def __init__(self,vocab_size, model_dimension):
        super().__init__()
        self.vocab_size = vocab_size
        self.model_dimension = model_dimension
        self.embed = nn.Embedding(num_embeddings=vocab_size, embedding_dim=model_dimension)
        self.lstm = nn.LSTM(input_size=model_dimension, hidden_size=model_dimension)
    
    def forward(self,x):
        x = self.embed(x)
        x, hidden = self.lstm(x)
        x = x.mean(axis=1)
        x = normalize2(x)
        return x

In [18]:
sub = Sub(5,3)

In [19]:
sub(x)

tensor([[ 0.7744, -0.4024, -0.4883],
        [ 0.8053, -0.4891, -0.3350]], grad_fn=<DivBackward0>)

In [20]:
def cosine_similarity(x1,x2):
    return x1 @ x2.T

In [21]:
class Siamese(nn.Module):
    def __init__(self, vocab_size, model_dimension):
        super().__init__()
        self.vocab_size = vocab_size
        self.model_dimension = model_dimension
        self.sub = Sub(vocab_size, model_dimension)
            
            
    def forward(self,x1,x2):
        x1 = self.sub(x1)
        x2 = self.sub(x2)
        return cosine_similarity(x1, x2)

In [22]:
siam = Siamese(5,3) 

In [23]:
x1 = torch.tensor([[1,2,3,4,0,0],
                     [1,1,1,0,0,0]])
x2 = torch.tensor([[0,1,4,0,0,0],
                     [1,1,2,0,0,0]])

In [24]:
siam(x1,x2)

tensor([[0.9788, 0.9891],
        [0.9887, 0.9969]], grad_fn=<MmBackward>)

In [25]:
for n,p in siam.named_parameters():
    print(n)

sub.embed.weight
sub.lstm.weight_ih_l0
sub.lstm.weight_hh_l0
sub.lstm.bias_ih_l0
sub.lstm.bias_hh_l0


Finalement, les deux subs partagent les mêmes poids donc on est bon